---
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 123
  Exclude:
    - 'lib/gitlab/client/*'
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 12

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'lib/gitlab/*'
    - 'lib/gitlab/client/*'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/gitlab/help_spec.rb'
